# -*- coding: utf-8 -*-
"""flask_web_server_create.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1399iGDlxHEJyPKFN9CRT16S536ce4k9M
"""

!git clone https://github.com/neonin04/flask-web-server.git

cd flask-web-server

!pip install flask-ngrok

!export FLASK_ENV=development
!flask run

from flask_ngrok import run_with_ngrok
from flask import Flask
app = Flask(__name__)
run_with_ngrok(app)   #starts ngrok when the app is run
@app.route("/")
def home():
    return "<h1>cps-animal-detection</h1>"
  
app.run()